名字: CI/CD工作流程

在:
推:
分支:
      - 师父
query为空pull_reque查询为空 pull_reque:
分支:
      - 师父

工作:
建筑:
    runs-on: ubuntu-latest  # Mesin Ubuntu untuk menjalankan perintah Debian
步骤:
      - 名字: 结账代码
用途: actions/checkout@v3
      
      - 名字: 设置Debian环境
跑: |
sudo apt-获取更新
sudo apt-get install -y build-essential # Sesuaikan kebutuhan Anda
      
      # Langkah untuk memulihkan cache
    
      # Langkah untuk menyimpan cache
      - name: LS opt
        run: |
ls ~/opt
        continue-on-error: true
        
      - name: Run script
        run: |
#Sesuaikan perintah ini untuk menjalankan企鹅jian proyek Anda
sh scripts/setup_linux_cross_compile.sh
      - name: Run Python
        run: |
python3 scripts/platform_builder.py --platform=android --arch=all --cmake_dir=$HOME/opt/cmake-3.25.2 --llvm_dir=$HOME/opt/llvm-15.0.6 --android_ndk_dir=$HOME/opt/ndk-r25b
          
      - name: LS
        run: |
低敏（ls）

      - name: Tree
        run: |
安装树
        continue-on-error: true
      - name: run tree
        run: |
树
        continue-on-error: true
        
      
    # continue-on-error: true
      - name: Upload 1
        uses: actions/upload-artifact@v4
        with:
            name: my-artifact
            path: /build # or path/to/artifact
        continue-on-error: true
 
      - name: Upload 2
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: build # or path/to/artifact
        continue-on-error: true

      - name: Tar
        run: tar -cvf build.tar /build
        continue-on-error: true
      - name: Upload 3
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: build.tar
        continue-on-error: true
